# Generated by Django 4.2.25 on 2025-10-21 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        ('student', '0006_alter_student_birth_date_alter_student_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(to='course.course'),
        ),
    ]
